import { ICommonCountries, ICommonInstitute } from './common.interface';

export const ICommonAge = ['10-15', '15-20', '20-25', '25-30', '30+'];
export const ICommonGender = ['male', 'female'];
export const ICommonDevice = ['Mobile', 'Tab', 'Laptop', 'Desktop'];
export const ICommonInternetType = ['Mobile', 'Broadband'];
export const ICommonExperience = ['1', '2', '3', '4', '5', '6', '7+'];
export const ICommonArea = ['Town', 'Village'];
export const ICommonStatus = ['Yes', 'No'];
export const ICommonJobType = ['Full-Time', 'Part-Time', 'Intern'];
export const ICommonJobPreference = ['Remotely', 'On-Office', 'Both'];
export const ICommonJobExperience = ['Yes', 'No'];
export const ICommonLevel = [
  'JSC/JDC/8pass',
  'Secondary',
  'Higher Secondary',
  'Diploma',
  'Bachelor/Honors',
  'Masters',
  'PhD (Doctor of Philosophy)',
];
export const Countries: ICommonCountries[] = [
  'Afghanistan',
  'Albania',
  'Algeria',
  'Andorra',
  'Angola',
  'Antigua and Barbuda',
  'Argentina',
  'Armenia',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bhutan',
  'Bolivia',
  'Bosnia and Herzegovina',
  'Botswana',
  'Brazil',
  'Brunei',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cabo Verde',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Central African Republic',
  'Chad',
  'Chile',
  'China',
  'Colombia',
  'Comoros',
  'Congo (Brazzaville)',
  'Congo (Kinshasa)',
  'Costa Rica',
  'Croatia',
  'Cuba',
  'Cyprus',
  'Czech Republic',
  'Denmark',
  'Djibouti',
  'Dominica',
  'Dominican Republic',
  'East Timor',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Eswatini',
  'Ethiopia',
  'Fiji',
  'Finland',
  'France',
  'Gabon',
  'Gambia',
  'Georgia',
  'Germany',
  'Ghana',
  'Greece',
  'Grenada',
  'Guatemala',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Honduras',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran',
  'Iraq',
  'Ireland',
  'Israel',
  'Italy',
  'Ivory Coast',
  'Jamaica',
  'Japan',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kiribati',
  'Korea North',
  'Korea South',
  'Kosovo',
  'Kuwait',
  'Kyrgyzstan',
  'Laos',
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Marshall Islands',
  'Mauritania',
  'Mauritius',
  'Mexico',
  'Micronesia',
  'Moldova',
  'Monaco',
  'Mongolia',
  'Montenegro',
  'Morocco',
  'Mozambique',
  'Myanmar',
  'Namibia',
  'Nauru',
  'Nepal',
  'Netherlands',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'North Macedonia',
  'Norway',
  'Oman',
  'Pakistan',
  'Palau',
  'Palestine',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Poland',
  'Portugal',
  'Qatar',
  'Romania',
  'Russia',
  'Rwanda',
  'Saint Kitts and Nevis',
  'Saint Lucia',
  'Saint Vincent and the Grenadines',
  'Samoa',
  'San Marino',
  'Sao Tome and Principe',
  'Saudi Arabia',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Slovakia',
  'Slovenia',
  'Solomon Islands',
  'Somalia',
  'South Africa',
  'South Sudan',
  'Spain',
  'Sri Lanka',
  'Sudan',
  'Suriname',
  'Sweden',
  'Switzerland',
  'Syria',
  'Taiwan',
  'Tajikistan',
  'Tanzania',
  'Thailand',
  'Togo',
  'Tonga',
  'Trinidad and Tobago',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Tuvalu',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom',
  'United States',
  'Uruguay',
  'Uzbekistan',
  'Vanuatu',
  'Vatican City',
  'Venezuela',
  'Vietnam',
  'Yemen',
  'Zambia',
  'Zimbabwe',
];

export const Institutes: ICommonInstitute[] = [
  'University of Dhaka',
  'University of Rajshahi	',
  'Bangladesh Agricultural University	',
  'Bangladesh University of Engineering & Technology	',
  'University of Chittagong	',
  'Jahangirnagar University	',
  'Islamic University, Bangladesh	',
  'Shahjalal University of Science & Technology	',
  'Khulna University	',
  'National University	',
  'Bangladesh Open University	',
  'Bangabandhu Sheikh Mujib Medical University	',
  'Bangabandhu Sheikh Mujibur Rahman Agricultural University	',
  'Hajee Mohammad Danesh Science & Technology University	',
  'Mawlana Bhashani Science & Technology University	',
  'Patuakhali Science And Technology University	',
  'Sher-e-Bangla Agricultural University	',
  'Chittagong University of Engineering & Technology	',
  'Rajshahi University of Engineering & Technology	',
  'Khulna University of Engineering & Technology	',
  'Dhaka University of Engineering & Technology	',
  'Noakhali Science & Technology University	',
  'Jagannath University	',
  'Comilla University	',
  'Jatiya Kabi Kazi Nazrul Islam University	',
  'Chittagong Veterinary and Animal Sciences University	',
  'Sylhet Agricultural University	',
  'Jessore University of Science & Technology	',
  'Pabna University of Science and Technology	',
  'Begum Rokeya University, Rangpur	',
  'Bangladesh University of Professionals	',
  'Bangabandhu Sheikh Mujibur Rahman Science & Technology University	',
  'Bangladesh University of Textiles	',
  'University of Barishal	wwwbuacbd',
  'Rangamati Science and Technology University	',
  'Bangabandhu Sheikh Mujibur Rahman Maritime University, ',
  'Bangladesh	',
  'Islamic Arabic University	',
  'Chittagong Medical University	',
  'Rajshahi Medical University	',
  'Rabindra University',
  'Bangabandhu Sheikh Mujibur Rahman Digital University Bangladesh	',
  'Sheikh Hasina University',
  'Khulna Agricultural University	',
  'Bangamata Sheikh Fojilatunnesa Mujib Science and Technology University	',
  'Sylhet Medical University	',
  'Bangabandhu Sheikh Mujibur Rahman Aviation And Aerospace University (BSMRAAU)	',
  'Chandpur Science and Technology University',
  'Bangabandhu Sheikh Mujibur Rahman University',
  'Hobiganj Agricultural University	',
  'Sheikh Hasina Medical University',
  'Kurigram Agricultural University	',
  'Sunamganj Science and Technology University	',
  'Bangabandhu Sheikh Mujibur Rahman Science & Technology University Pirojpur',
  'Bangabandhu Sheikh Mujibur Rahman University Naogaon',
  'North South University',
  'University of Science & Technology Chittagong	',
  'Independent University, Bangladesh',
  'Central Womens University',
  'International University of Business Agriculture & Technology	u',
  'International Islamic University Chittagong	',
  'Ahsanullah University of Science and Technology	',
  'American International University-Bangladesh	',
  'East West University	',
  'University of Asia Pacific	',
  'Gono Bishwabidyalay	',
  'Asian University of Bangladesh	',
  'Dhaka International University	',
  'Manarat International University	',
  'BRAC University	',
  'Leading University	',
  'BGC Trust University Bangladesh	',
  'Sylhet International University	',
  'University of Development Alternative	',
  'Premier University	',
  'Southeast University	',
  'Daffodil International University	',
  'Stamford University Bangladesh	',
  'State University of Bangladesh (SUB)	',
  'City University',
  'Prime University	',
  'Northern University Bangladesh	',
  'Southern University Bangladesh ',
  'Green University of Bangladesh	',
  'Pundra University of Science & Technology	',
  'World University of Bangladesh	',
  'Shanto-Mariam University of Creative Technology	',
  'The Millennium University',
  'Eastern University	',
  'Metropolitan University	',
  'Uttara University',
  'United International University	',
  'University of South Asia	',
  'Bangladesh University of Business & Technology	',
  'Presidency University	wwwpresidencyedubd',
  'University of Information Technology & Sciences	',
  'Primeasia University',
  'Royal University of Dhaka	',
  'University of Liberal Arts Bangladesh	',
  'Atish Dipankar University of Science & Technology',
  'Bangladesh Islami University	',
  'ASA University Bangladesh	',
  'East Delta University',
  'Varendra University	',
  'Hamdard University Bangladesh	',
  'BGMEA University of Fashion & Technology(BUFT)',
  'North East University Bangladesh	',
  'First Capital University of Bangladesh	',
  'Ishakha International University, Bangladesh	',
  'ZH Sikder University of Science & Technology	',
  'Exim Bank Agricultural University, Bangladesh	',
  'North Western University	',
  'Khwaja Yunus Ali University',
  'Sonargaon University	',
  'Feni University	',
  'Port City International University	',
  'Bangladesh University of Health Sciences	',
  'Chittagong Independent University	',
  'Notre Dame University Bangladesh	',
  'Times University, Bangladesh	',
  'North Bengal International University	',
  'Fareast International University	',
  'Rajshahi Science & Technology University (RSTU)',
  'Sheikh Fazilatunnesa Mujib University	',
  'Coxs Bazar International University',
  'R P Shaha University	',
  'German University Bangladesh	',
  'Global University Bangladesh	',
  'CCN University of Science & Technology	',
  'Bangladesh Army University of Science and Technology(BAUST)',
  'Bangladesh Army University of Engineering and Technology (BAUET)',
  'Bangladesh Army International University of Science & Technology(BAIUST) ',
  'The International University of Scholars	',
  'Canadian University of Bangladesh',
  'NPI University of Bangladesh	',
  'Northern University of Business & Technology, Khulna	',
  'Rabindra Maitree University, Kushtia	',
  'University of Creative Technology',
  'Central University of Science and Technology	',
  'Tagore University of Creative Arts',
  'University of Global Village	',
  'Rupayan AKM Shamsuzzoha University',
];
